config/routes.rb
Rails.application.routes.draw do
  namespace :customer do
    get '/order_place', :to => 'checkouts#orderplace'
    resources :carts ,:products , :orders, :checkouts
  end
  # get 'categories/index'

  namespace :seller do
    resources :products
  end

  namespace :admin do
    resources :main
  end
  
  root to: "main#index"
  
  resources :main, :categories,:admin, :seller,:products
  devise_for :accounts, controllers: {
        sessions: 'accounts/sessions',
        registrations: 'accounts/registrations'
      }


end

app/models/account.rb
class Account < ApplicationRecord
  # has_and_belongs_to_many :roles, join_table: :accounts_roles
  
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  
  
  has_many :carts
  has_many :cart_items
  has_many :products
  has_many :orders
       
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :account
  has_many :cart_items
  belongs_to :order
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :subcategories ,class_name: 'Category', foreign_key: 'parent_id'
    has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :account
    has_one :cart

end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image
    belongs_to :category
    has_many :products
    has_many :cart_items
    belongs_to :account
    has_many :cart_items,dependent: :destroy
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :accounts, :join_table => :accounts_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/controllers/admin/main_controller.rb
class Admin::MainController < ApplicationController
    def index
        @sellers = Role.second.accounts 
        @customers = Role.third.accounts
    end

    def edit
        @seller = Account.find(params[:id])
    end
        
    def update
        @seller = Account.find(params[:id])
        
      if @seller.update(account_params)
        redirect_to @seller
      else
        render :edit, status: :unprocessable_entity
      end
    end
        
    def destroy
        @seller = Account.find(params[:id])
        @seller.destroy
        
        redirect_to root_path, status: :see_other
    end
        
    private
    def account_params
        params.require(:account).permit(:email, :firsname,:lastname,:age,:gender,:phone,:address)
    end
        

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # protect_from_forgery with: :null_session
    def after_sign_in_path_for(resource)
        if current_account.roles.first[:name]== "admin"
            admin_main_index_path(current_account)
        elsif current_account.roles.first[:name] == "seller"     
            seller_products_path
        else
            customer_products_path(current_account)
        end

    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    @cloths = Category.find(1).subcategories
    @electric = Category.find(5).subcategories
  end
  def show
    @category = Category.find(params[:id])
  end


end

app/controllers/customer/carts_controller.rb
class Customer::CartsController < ApplicationController
  
  def index
    @cart_items = current_account.carts.where(isorder:false).first.cart_items
  end
  def new

    @cart_item = current_account.carts.first.cart_items.where(product_id: params[:product_id])
    if current_account.carts.first.cart_items.where(product_id: params[:product_id]).empty? 
      @cart_item = current_account.carts.first.cart_items.new(price: params[:price],quantity: 1,product_id:params[:product_id])
      @cart_item.save
  
    else
      @cart_item.update(quantity:(@cart_item.first.quantity + 1))
    end
  
    redirect_to customer_carts_path
  
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
  def index
    @products = Product.paginate(page: params[:page], per_page: 4)
    @categories = Category.all
    @cloths = Category.find(1).subcategories
    @electric = Category.find(5).subcategories
  end 

  def show
    @account = current_account
   
  end

  private

  def account_params
    params.require(:account).permit(:email, :name)
  end

end

app/helpers/admin/main_helper.rb
module Admin::MainHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customer/carts_helper.rb
module Customer::CartsHelper
end

app/helpers/customer/checkouts_helper.rb
module Customer::CheckoutsHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/helpers/customer/products_helper.rb
module Customer::ProductsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/seller/products_helper.rb
module Seller::ProductsHelper
end

app/helpers/seller_helper.rb
module SellerHelper
end

app/views/admin/main/index.html.erb
<style>

body{
background-color: black;
color: greenyellow;
}

td,th {
background: -webkit-linear-gradient(#eee, #333);
-webkit-background-clip: text;
-webkit-text-fill-color: transparent;
}
button a{
text-decoration: none !important;
color: white !important;
}
.table{
color: greenyellow;
}

</style>


<div class="container">
<h1>Your Sellers</h1>
<table class="table">
<thead>
<tr>
<th scope="col">ID</th>
<th scope="col">Email</th>
<th scope="col">First Name</th>
<th scope="col">Last Name</th>
<th scope="col">Age</th>
<th scope="col">Gender</th>
<th scope="col">Phone</th>
<th scope="col">Address</th>
<th scope="col">Edit</th>
<th scope="col">Delete</th>
</tr>
</thead>
<tbody>
<% @sellers.each do |ac|%>


<tr>
<th scope="row"><%= ac.id %></th>
<td><%= ac.firstname%></td>
<td><%= ac.lastname%></td>
<td><%= ac.email%></td>
<td><%= ac.age%></td>
<td><%= ac.gender%></td>
<td><%= ac.phone%></td>
<td><%= ac.address%></td>
</tr>
<% end %>
</tbody>

</table>


<h1>Your Customers</h1>
<table class="table">
<thead>
<tr>
<th scope="col">ID</th>
<th scope="col">Email</th>
<th scope="col">First Name</th>
<th scope="col">Last Name</th>
<th scope="col">Age</th>
<th scope="col">Gender</th>
<th scope="col">Phone</th>
<th scope="col">Address</th>
<th scope="col">Edit</th>
<th scope="col">Delete</th>
</tr>
</thead>
<tbody>


<% @customers.each do |ca|%>
<tr>
<th scope="row"><%= ca.id %></th>
<td><%= ca.firstname%></td>
<td><%= ca.lastname%></td>
<td><%= ca.email%></td>
<td><%= ca.age%></td>
<td><%= ca.gender%></td>
<td><%= ca.phone%></td>
<td><%= ca.address%></td>
</tr>
<% end %>
</tbody>

</table>
</div>

app/views/main/index.html.erb
  <style>
  .table{
    color: greenyellow;
  }
  h2{
    display: flex;
    font-size:120px;
    color: greenyellow;
    text-align:center;
  }
  .card-img-top{
    width: 100%;
    height: 250px;
  }

  </style>



<% if account_signed_in? %>
<h2>WELLCOME TO E-COMMERCE WEBSITE</h2>
<% end %>

<div class="container">
    <div class="row">
    <% @products.each do |pro| %>
      <div class="col">

        <div class="card" style="width: 18rem;">

          <%= image_tag (url_for(pro.image)) ,class:"card-img-top"%>

          <div class="card-body">
            <h5 class="card-title"></h5>
            <p class="card-text"><%= pro.description %></p>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><span class="text-decoration-line-through">Actual Price -<%= pro.actual_price %></span></li>
            <li class="list-group-item">Current Price -<%= pro.current_price %></li>
          </ul>
          <div class="card-body">
              <a href="#" class="btn btn-outline-success"><i class="bi bi-cart2"></i> Add To Cart</a>
              <%# <%= link_to <i class="bi bi-cart2">,new_customer_cart_path(product_id:pro.id,price:pro.current_price),class:"btn btn-outline-success"%> 
              <a href="#" class="btn btn-outline-primary">Buy Now</a>
          </div>
        </div>
      </div>
      <% end %>
    </div>
</div>


 <div class="row">
<%= will_paginate @products, class: "digg_pagination mt-2 col-4 offset-4" %>
 </div>

app/views/main/show.html.erb
<style>

    .container {
        position: absolute;
        top: 0;
        left: 0;
        padding:60px 30px;
        color:#000;
        width: 500px; 
        height:600px;
        border-bottom-right-radius:30px;
        background-color: #fff;
        box-shadow: 0 2px 4px 2px rgba(255,255,255,0.2);
}

.raja{
    text-align:center;
    color:red ;
}

</style>
<div class="container">
<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <td><%= @account.id%></td>
        </tr>
    </thead>
    <thead>
        <tr> 
            <th scope="col">Email</th>
            <td><%= @account.email%></td>        
        </tr>
    </thead>
    <thead>
        <tr> 
            <th scope="col">First Name</th>
            <td><%= @account.firstname%></td>        
        </tr>
    </thead>
    <thead>
        <tr> 
            <th scope="col">Last Name</th>
            <td><%= @account.lastname%></td>        
        </tr>
    </thead>
    <thead>
        <tr> 
            <th scope="col">Age</th>
            <td><%= @account.age%></td>        
        </tr>
    </thead>
    <thead>
        <tr> 
            <th scope="col">Gender</th>
            <td><%= @account.gender%></td>        
        </tr>
    </thead>
    <thead>
        <tr> 
            <th scope="col">phone</th>
            <td><%= @account.phone%></td>     
        </tr>
    </thead>
    <thead>
        <tr> 
            <th scope="col">Address</th>
            <td><%= @account.address%></td>        
        </tr>
    </thead>
    <thead>
        <tr> 
            <th scope="col">Edit</th>
            <td><%= link_to "Edit" , edit_account_registration_path, class:"btn btn-success" %></td>        
        </tr>
    </thead>
    </table>

    <a href="http://localhost:3000" class="btn btn-primary">Back to Home</a>
    </div>