config/routes.rb
Rails.application.routes.draw do
  namespace :customer do
    get '/order_place', :to => 'checkouts#orderplace'
    resources :carts ,:products , :orders, :checkouts
  end
  # get 'categories/index'

  namespace :seller do
    resources :products
  end

  namespace :admin do
    resources :main
  end
  
  root to: "main#index"
  
  resources :main, :categories,:admin, :seller,:products
  devise_for :accounts, controllers: {
        sessions: 'accounts/sessions',
        registrations: 'accounts/registrations'
      }


end

app/models/account.rb
class Account < ApplicationRecord
  # has_and_belongs_to_many :roles, join_table: :accounts_roles
  
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  
  
  has_many :carts
  has_many :cart_items
  has_many :products
  has_many :orders
       
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :account
  has_many :cart_items
  belongs_to :order
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :subcategories ,class_name: 'Category', foreign_key: 'parent_id'
    has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :account
    has_one :cart

end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image
    belongs_to :category
    has_many :products
    has_many :cart_items
    belongs_to :account
    has_many :cart_items,dependent: :destroy
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :accounts, :join_table => :accounts_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # protect_from_forgery with: :null_session
    def after_sign_in_path_for(resource)
        if current_account.roles.first[:name]== "admin"
            admin_main_index_path(current_account)
        elsif current_account.roles.first[:name] == "seller"     
            seller_products_path
        else
            customer_products_path(current_account)
        end

    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    @cloths = Category.find(1).subcategories
    @electric = Category.find(5).subcategories
  end
  def show
    @category = Category.find(params[:id])
  end


end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
  def index
    @products = Product.paginate(page: params[:page], per_page: 4)
    @categories = Category.all
    @cloths = Category.find(1).subcategories
    @electric = Category.find(5).subcategories
  end 

  def show
    @account = current_account
   
  end

  private

  def account_params
    params.require(:account).permit(:email, :name)
  end

end

app/helpers/admin/main_helper.rb
module Admin::MainHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customer/carts_helper.rb
module Customer::CartsHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/seller/products_helper.rb
module Seller::ProductsHelper
end

app/helpers/seller_helper.rb
module SellerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flipkart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>
  <style>

  .ff{
    font-size:20px;
  }

  
  </style>
  <body>
  <%= render partial: "share/navbar" %>
  <div>
    <p class="alert alert-success" role="alert"><%= notice %></p>
       <p class="alert alert-danger" role="alert"><%= alert %></p>
       </div>
    <%= yield %>
  </body>
</html>

app/views/share/_navbar.html.erb
<style>
nav {
  z-index: 1;
}
</style>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <div>
  <% if account_signed_in? %>

  <%= link_to "Profile", main_path(current_account),class:"navbar-brand" %>
  <% else %>
  <h1 class="navbar-brand">Wellcome</h1>
        <% end %>  
    </div>

        <% if account_signed_in? %>
          <h4 class="navbar-link"><%= current_account.roles.first[:name] %></h4>
        <%else%>
          <h4 class="navbar-link">Please Log in</h4>
        <% end %>

      
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="http://localhost:3000">Home</a>
        </li>
        <li class="nav-item">
          <% if account_signed_in? %>
          <%= link_to "Log Out" ,destroy_account_session_path, data:{turbo_method:  :delete} , class:"nav-link" %>
          <% else %>
          <%= link_to "Log in", new_account_session_path ,class:"nav-link" %>
          <% end %>
          </li>
          <li class="nav-item">
          <% if account_signed_in? %>
          <%= link_to "Edit" , edit_account_registration_path, class:"nav-link" %>
          <% end %>
          </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
         
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <%if account_signed_in? %>
      <% if current_account.roles.first[:name]== "customer" %>
      <h1>
          <a class="nav-link" href="http://localhost:3000/customer/carts"><i class="bi bi-cart-check-fill"></i></a>
      </h1>
        <% end %>
        <% end %>
    </div>
  </div>
</nav>