config/routes.rb
Rails.application.routes.draw do
  namespace :customer do
    get '/order_place', :to => 'checkouts#orderplace'
    resources :carts ,:products , :orders, :checkouts
  end
  # get 'categories/index'

  namespace :seller do
    resources :products
  end

  namespace :admin do
    resources :main
  end
  
  root to: "main#index"
  
  resources :main, :categories,:admin, :seller,:products
  devise_for :accounts, controllers: {
        sessions: 'accounts/sessions',
        registrations: 'accounts/registrations'
      }


end

app/models/account.rb
class Account < ApplicationRecord
  # has_and_belongs_to_many :roles, join_table: :accounts_roles
  
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  
  
  has_many :carts
  has_many :cart_items
  has_many :products
  has_many :orders
       
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :account
  has_many :cart_items
  belongs_to :order
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :subcategories ,class_name: 'Category', foreign_key: 'parent_id'
    has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :account
    has_one :cart

end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image
    belongs_to :category
    has_many :products
    has_many :cart_items
    belongs_to :account
    has_many :cart_items,dependent: :destroy
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :accounts, :join_table => :accounts_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/controllers/admin/main_controller.rb
class Admin::MainController < ApplicationController
    def index
        @sellers = Role.second.accounts 
        @customers = Role.third.accounts
    end

    def edit
        @seller = Account.find(params[:id])
    end
        
    def update
        @seller = Account.find(params[:id])
        
      if @seller.update(account_params)
        redirect_to @seller
      else
        render :edit, status: :unprocessable_entity
      end
    end
        
    def destroy
        @seller = Account.find(params[:id])
        @seller.destroy
        
        redirect_to root_path, status: :see_other
    end
        
    private
    def account_params
        params.require(:account).permit(:email, :firsname,:lastname,:age,:gender,:phone,:address)
    end
        

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # protect_from_forgery with: :null_session
    def after_sign_in_path_for(resource)
        if current_account.roles.first[:name]== "admin"
            admin_main_index_path(current_account)
        elsif current_account.roles.first[:name] == "seller"     
            seller_products_path
        else
            customer_products_path(current_account)
        end

    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    @cloths = Category.find(1).subcategories
    @electric = Category.find(5).subcategories
  end
  def show
    @category = Category.find(params[:id])
  end


end

app/controllers/customer/carts_controller.rb
class Customer::CartsController < ApplicationController
  
  def index
    @cart_items = current_account.carts.where(isorder:false).first.cart_items
  end
  def new

    @cart_item = current_account.carts.first.cart_items.where(product_id: params[:product_id])
    if current_account.carts.first.cart_items.where(product_id: params[:product_id]).empty? 
      @cart_item = current_account.carts.first.cart_items.new(price: params[:price],quantity: 1,product_id:params[:product_id])
      @cart_item.save
  
    else
      @cart_item.update(quantity:(@cart_item.first.quantity + 1))
    end
  
    redirect_to customer_carts_path
  
  end

end

app/controllers/customer/products_controller.rb
class Customer::ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
  def index
    @products = Product.paginate(page: params[:page], per_page: 4)
    @categories = Category.all
    @cloths = Category.find(1).subcategories
    @electric = Category.find(5).subcategories
  end 

  def show
    @account = current_account
   
  end

  private

  def account_params
    params.require(:account).permit(:email, :name)
  end

end

app/controllers/seller/products_controller.rb
class Seller::ProductsController < ApplicationController

def index
    @products = current_account.products       
end
def show
    @product = Product.find(params[:id])
  end

  def new
    @product = current_account.products.new
  end

  def create
    @product = current_account.products.new(product_params)

    if @product.save
      redirect_to [:seller,@product]
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to [:seller,@product]
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def product_params
      params.require(:product).permit(:name, :actual_price,:current_price,:description,:image,:category_id)
    end

end

app/helpers/admin/main_helper.rb
module Admin::MainHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customer/carts_helper.rb
module Customer::CartsHelper
end

app/helpers/customer/checkouts_helper.rb
module Customer::CheckoutsHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/helpers/customer/products_helper.rb
module Customer::ProductsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/seller/products_helper.rb
module Seller::ProductsHelper
end

app/helpers/seller_helper.rb
module SellerHelper
end

app/views/seller/products/_form.html.erb
<style>
  a{
    
    color:greenyellow;
  }  
.container{
    margin:auto;
    position:absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    padding:25px;
    width: 35%;
    color:greenyellow;
    border-radius:25px;
    box-shadow: 0px 0px 8px 2px greenyellow;
  }
  .radio{
    margin: 0 10px 0 0;
  }
  
  .inp{
    
    width: 100%;
    height: auto;
    margin:5px;
    font-size:20px;
  }
  .lab{
    color:greenyellow;
    font-size:20px;
}


</style>







<%= form_with model: [:seller,@product] do |form| %>
<div class="container">
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name,class:"inp" %>
    
  </div>

  <div>
    <%= form.label :actual_price %><br>
    <%= form.text_field :actual_price ,class:"inp"%><br>
   
    
  </div>
  <div>
    <%= form.label :current_price %><br>
    <%= form.text_field :current_price ,class:"inp"%><br>
    
  </div>
  <div>
    <%= form.label :description %><br>
    <%= form.text_field :description,class:"inp" %><br>
    
  </div>
  <div>
  <%= form.label :images %><br>
  <%= form.file_field :image %>
  </div>

  <div>
    <%= form.label :category_id %><br>
    <%= form.text_field :category_id ,class:"inp"%><br>
    
  </div>

  <div>
    <%= form.submit %>
  </div>

<div>
<% end %>

app/views/seller/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "form", product: @product %>

app/views/seller/products/index.html.erb
  <style>

  body{
    background-color: black;
  }
  .table{
    color: greenyellow;
  }
  h1{
    display: flex;
    font-size:120px;
    color: greenyellow;
    text-align:center;
  }
.card-img-top{
  width:100%;
  height: 250px;
}
  </style>













<div class="container">
<% if account_signed_in? %>
<h1>WELLCOME <%= current_account.firstname%> <%= current_account.lastname%></h1>
<% end %>
<div class="row">
<% @products.each do |pro| %>
<div class="col">
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <%= image_tag (url_for(pro.image)) ,class:"card-img-top"%>
      <h5 class="card-title"><%= pro.name %></h5>
      <p class="card-text"><%= pro.description %></p>
    </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><span class="text-decoration-line-through">Actual Price -<%= pro.actual_price %></span></li>
        <li class="list-group-item">Current Price -<%= pro.current_price %></li>
      </ul>
      <div class="container">
        <%= link_to "Show", seller_product_path(pro) ,class:"btn btn-primary"%>
        <%= link_to "Edit", edit_seller_product_path(pro) ,class:"btn btn-success"%>
        <%= link_to "Destroy", seller_product_path(pro),class:"btn btn-danger",data: {
                          turbo_method: :delete,
                          turbo_confirm: "Are you sure?"
                        } %>
      </div>
  </div>
</div>
  <% end %>
</div>
<%= link_to "New Product", new_seller_product_path,class:"btn btn-primary"%>
</div>

app/views/seller/products/new.html.erb
<%= render "form", product: @product %>

app/views/seller/products/show.html.erb
<div class="container">
<div class="card" style="width: 18rem;">
  <%= image_tag (url_for(@product.image)) ,class:"card-img-top"%>
  <div class="card-body">
    <h5 class="card-title"><%= @product.name%></h5>
    <p class="card-text"><%= @product.description%></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Actual Price -<%= @product.actual_price%></li>
    <li class="list-group-item">Current Price -<%= @product.current_price%></li>
    <li class="list-group-item">Vestibulum at eros</li>
  </ul>
  <div class="card-body">
    <a href="#" class="card-link">Card link</a>
    <a href="#" class="card-link">Another link</a>
  </div>
</div>
</div>