config/routes.rb
Rails.application.routes.draw do
  namespace :customer do
    get '/order_place', :to => 'checkouts#orderplace'
    resources :carts ,:products , :orders, :checkouts
  end
  # get 'categories/index'

  namespace :seller do
    resources :products
  end

  namespace :admin do
    resources :main
  end
  
  root to: "main#index"
  
  resources :main, :categories,:admin, :seller,:products
  devise_for :accounts, controllers: {
        sessions: 'accounts/sessions',
        registrations: 'accounts/registrations'
      }


end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :account
  has_many :cart_items
  belongs_to :order
end

app/controllers/customer/carts_controller.rb
class Customer::CartsController < ApplicationController
  
  def index
    @cart_items = current_account.carts.where(isorder:false).first.cart_items
  end
  def new

    @cart_item = current_account.carts.first.cart_items.where(product_id: params[:product_id])
    if current_account.carts.first.cart_items.where(product_id: params[:product_id]).empty? 
      @cart_item = current_account.carts.first.cart_items.new(price: params[:price],quantity: 1,product_id:params[:product_id])
      @cart_item.save
  
    else
      @cart_item.update(quantity:(@cart_item.first.quantity + 1))
    end
  
    redirect_to customer_carts_path
  
  end

end

app/controllers/customer/checkouts_controller.rb
class Customer::CheckoutsController < ApplicationController

    def index

        session = Stripe::Checkout::Session.create({
            mode: 'payment',
            # Remove the payment_method_types parameter
            # to manage payment methods in the Dashboard
            payment_method_types: ['card'],
            line_items: [{
              price_data: {
              # The currency parameter determines which
              # payment methods are used in the Checkout Session.
                currency: 'inr',
                  product_data: {
                    name: 'Total',
                  },
                  unit_amount: 200000,
                },
                quantity: 1,
              }],
              success_url: 'https://localhost:3000/customer/order_place?session_id={CHECHOUT_SESSION_ID}',
              cancel_url: 'https://example.com/cancel',
            })
            redirect_to session.url, allow_other_host: true
            

    end
    def orderplace
        @details = Stripe::Checkout::Session.retrieve(params[:session_id])
        @order = Order.first.update(transaction_id:@details.payment_intent)

    end

end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
    def new
        @cart = Cart.find(params[:cart_id])
        @order = Order.new
        @total = params[:total_price]
    end

    def create
        @order = current_account.orders.new(order_params)
        # @order[:total] = params[:order_id][:total].to_f
        if @order.save
            redirect_to customer_checkouts_path
        else 
            render :show,status: :unprocessable_entity
        end
    end

    private
    def order_params
        params.require(:order).permit(:name, :email, :address, :number, :total)

    end
end

app/controllers/customer/products_controller.rb
class Customer::ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  
end

app/helpers/customer/carts_helper.rb
module Customer::CartsHelper
end

app/helpers/customer/checkouts_helper.rb
module Customer::CheckoutsHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/helpers/customer/products_helper.rb
module Customer::ProductsHelper
end

app/views/customer/carts/index.html.erb
<style>
.gradient-custom {
/* fallback for old browsers */
background: #6a11cb;

/* Chrome 10-25, Safari 5.1-6 */
background: -webkit-linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1));

/* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
background: linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1))
}
</style>



<section class="h-100 gradient-custom">
  <div class="container py-5">
    <div class="row d-flex justify-content-center my-4">
      <div class="col-md-8">
        <div class="card mb-4">
          <div class="card-header py-3">
            <h5 class="mb-0">Cart - 2 items</h5>
          </div>
          <div class="card-body">
            <!-- Single item -->
            <% @cart_items.each_with_index do |cart, index| %>
            <div class="row">
              <div class="col-lg-3 col-md-12 mb-4 mb-lg-0">
                <!-- Image -->
                <div class="bg-image hover-overlay hover-zoom ripple rounded" data-mdb-ripple-color="light">
                  <img class="w-100" alt="<%=cart.product.name%>" src="<%=(url_for(cart.product.image))%>">
                  <a href="#!">
                    <div class="mask" style="background-color: rgba(251, 251, 251, 0.2)"></div>
                  </a>
                </div>
                <!-- Image -->
              </div>

              <div class="col-lg-5 col-md-6 mb-4 mb-lg-0">
                <!-- Data -->
                <p><strong> <%= cart.product.name %></strong></p>
                <%# <p>Color: blue</p> %>
                <p><%= cart.product.description%></p>
                <button type="button" class="btn btn-primary btn-sm me-1 mb-2" data-mdb-toggle="tooltip"
                  title="Remove item">
                  <i class="fas fa-trash"></i>
                </button>
                <button type="button" class="btn btn-danger btn-sm mb-2" data-mdb-toggle="tooltip"
                  title="Move to the wish list">
                  <i class="fas fa-heart"></i>
                </button>
                <!-- Data -->
              </div>

              <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
                <!-- Quantity -->
                <div class="d-flex mb-4" style="max-width: 300px">
                  <button class="btn btn-primary px-3 me-2"
                    onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                    <i class="fas fa-minus"></i>
                  </button>

                  <div class="form-outline">
                    <input id="form1" min="0" name="quantity" value="1" type="number" class="form-control" />
                    <label class="form-label" for="form1">Quantity</label>
                  </div>
                  <button class="btn btn-primary px-3 ms-2"
                    onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                    <i class="fas fa-plus"></i>
                  </button>
                </div>
                <!-- Quantity -->

                <!-- Price -->
                <p class="text-start text-md-center">
                    <strong>₹ <%=cart.price * cart.quantity%></strong>
                </p>
                <!-- Price -->
              </div>
            </div>
            <hr class="my-4" />
            <% end %>
            <!-- Single item -->
          </div>
        </div>
        <div class="card mb-4">
          <div class="card-body">
            <p><strong>Expected shipping delivery</strong></p>
            <p class="mb-0">12.10.2020 - 14.10.2020</p>
          </div>
        </div>
        <div class="card mb-4 mb-lg-0">
          <div class="card-body">
            <p><strong>We accept</strong></p>
            <img class="me-2" width="45px"
              src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/visa.svg"
              alt="Visa" />
            <img class="me-2" width="45px"
              src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/amex.svg"
              alt="American Express" />
            <img class="me-2" width="45px"
              src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/mastercard.svg"
              alt="Mastercard" />
            <img class="me-2" width="45px"
              src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce/includes/gateways/paypal/assets/images/paypal.webp"
              alt="PayPal acceptance mark" />
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4">
          <div class="card-header py-3">
            <h5 class="mb-0">Summary</h5>
          </div>
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li
                class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                Products
                <span>₹ <%= @cart_items.sum("price * quantity")%></span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                Shipping
                <span>Free</span>
              </li>
              <li
                class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                <div>
                  <strong>Total amount</strong>
                  <strong>
                    <p class="mb-0">(including GST)</p>
                  </strong>
                </div>
                <span><strong>₹ <%= @cart_items.sum("price * quantity")%></strong></span>
              </li>
            </ul>
            
             <%= link_to "Place Order" ,new_customer_order_path(cart_id:@cart_items.first.cart_id,total_price:@cart_items.sum("price * quantity")),class:"btn btn-primary btn-lg btn-block"%>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>